# Generated by Django 4.1.7 on 2023-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['date_of_refusal'], 'verbose_name': 'Рекламации', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='service_company',
            options={'verbose_name': 'Сервисные компании', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='type_maintenance',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Вид ТО'},
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_number',
            field=models.TextField(max_length=50, verbose_name='Номер ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.TextField(max_length=17, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number',
            field=models.TextField(db_index=True, max_length=17, unique=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steerable_axle_number',
            field=models.TextField(max_length=50, verbose_name='Номер управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_number',
            field=models.TextField(max_length=50, verbose_name='Номер трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.IntegerField(verbose_name='Наработка мотто/часов'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order',
            field=models.TextField(max_length=50, verbose_name='Номер заказа-наряда'),
        ),
    ]
